### PR TITLE
Fixed parenthesis for the shorthand if.

### PR DESCRIPTION
**Pull request by josh-tepper**
@kevinmost -- meet Rok, who has been working with us on java.  He uncovered an issue with some of your generated code.  Take a look at this fix.

@rok-povsic #

### CODE REVIEW

**Comment by josh-tepper** [comment]
Compare these two pieces of code.  The first is generated code from a class that does not use your extension:
```
...
return ((this.id == null) ? (that.id() == null) : this.id.equals(that.id()))
      && ((this.createdAt == null) ? (that.createdAt() == null) : this.createdAt.equals(that.createdAt()))
      && (this.inputValue.equals(that.inputValue()))
      && (this._metadata.equals(that._metadata()))
      && (this.concepts.equals(that.concepts()))
      && ((this.geo == null) ? (that.geo() == null) : this.geo.equals(that.geo()));
```

The second is generated code from a class that uses the `@IgnoreForHashCodeEquals`:
```
return
    (this.id() == null) ? (that.id() == null) : this.id().equals(that.id())
        && (this.name() == null) ? (that.name() == null) : this.name().equals(that.name())
        && (this.createdAt() == null) ? (that.createdAt() == null) : this.createdAt().equals(that.createdAt())
        && (this.appID() == null) ? (that.appID() == null) : this.appID().equals(that.appID())
        && (this.modelVersion() == null) ? (that.modelVersion() == null) : this.modelVersion().equals(that.modelVersion())
        // _outputInfo (type: clarifai2.dto.model.output_info.OutputInfo) skipped due to @IgnoreForHashCodeEquals annotation
        // client (type: clarifai2.api.ClarifaiClient) skipped due to @IgnoreForHashCodeEquals annotation
      ;
```
Note that in both cases, a ternary operator is used to handle checking nullable values.  However, in the second case, the ternary expression is not put in parenthesis.  The problem is that '?' has lower precedence than '&&', so the boolean expression on which ? operates includes the entirety of everything before it, including the previous ternary expressions.

**Comment by kevinmost** [comment]
Hey @rok-povsic and @josh-tepper. This looks great! Thanks for the PR and for catching a very subtle bug. 

Gonna merge this in now, so you can hopefully start depending on it immediately with the new commit SHA via Jitpack.

**Comment by josh-tepper** [comment]
Thanks!

**Comment by rok-povsic** [comment]
Great, thank you!

**Pull request merged**
